### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by Xris01** [m3u8-segmenter/m3u8-segmenter#21]
Hi,

using a recent FFMPEG release (v38280), compilation stops with an error :

m3u8-segmenter.c:395: error: 'URL_WRONLY' undeclared (first use in this function)
m3u8-segmenter.c:395: error: (Each undeclared identifier is reported only once

Please, advise.

Thanks,
Xris

**Comment by rodislav** [comment]
same here

**Comment by rodislav** [comment]
ok, I did it :)

add to Makefile.am this:
m3u8-segmenter: m3u8-segmenter.o
gcc -o m3u8-segmenter m3u8-segmenter.c -l:libavformat.so

you can read about these lines here
http://www.cs.usask.ca/staff/oster/makefiles.html

in netbeans create project with existing sources add custom makefile - Makefile.am

then build, i you want to run it

in line ~234 add this
options.input_file = "PATH_TO_TS_FILE";
options.m3u8_file = "tests/test.m3u8";
options.segment_duration = 10;

in while near line 284 put - false, instead of opt != -1, to avoid argv parsing, and you can test quickly how its working

**Comment by johnf** [comment]
This seems to currently work with latest ffmpeg
